expr : term ((PLUS|MINUS) term)*

term : factor ((MUL|DIV) factor)*

factor : INT|FLOAT
       : (PLUS|MINUS) factor
       : LPAREN expr RPAREN

PLUS : '+'
MINUS : '-'
MUL : '*'
DIV : '/'
INT : [0-9]+
FLOAT : [0-9]*.[0-9]*
LPAREN : '('
RPAREN : ')'