expr : KEYWORD:VAR IDENTIFIER EQ expr
     : term ((PLUS|MINUS) term)*

term : factor ((MUL|DIV) factor)*

factor : (PLUS|MINUS) factor
       : power

power : atom (POW factor)*

factor : INT|FLOAT|IDENTIFIER
       : LPAREN expr RPAREN

PLUS : '+'
MINUS : '-'
MUL : '*'
DIV : '/'
POW : '^'
EQ  : '='
INT : [0-9]+
FLOAT : [0-9]*.[0-9]*
LPAREN : '('
RPAREN : ')'
KEYWORD: 'VAR'
IDENTIFIER: ASCII (ASCII|INT|'_')* 